# Generated by Django 4.2.7 on 2024-01-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact_image_alter_contact_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='address',
        ),
    ]
